[package]
name = "rxml_validation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rxml = { path = "../rxml" }
rxml_proc = { path = "../rxml_proc" }
